### ISSUE TITLE
В api не работает readSet.

### ISSUE THREAD

**Issue by mandryka** [bluzphp/framework#324]
Когда не отправляешь $primary, все равно заходит в readOne  и возвращает exception - Record not found.

**Comment by AntonShevchuk** [comment]
Попробовал, работает нормально - `/test/rest/?offset=0&limit=10`

**Comment by hunterok727** [comment]
речь же шла о api модуле, а не о rest контроллере as is

**Comment by AntonShevchuk** [comment]
тогда наверное речь о skeleton'e?

**Comment by hunterok727** [comment]
полагаю Bluz\Controller\Rest::__construct()
```php
    if (sizeof($params)) {
        $this->primary = explode('-', array_shift($params));
    }
```
фиксится
```php
    if (sizeof($params) && isset($params[0])) {
        $this->primary = explode('-', array_shift($params));
    }
```
Или же возможно в скелетоне в модуле api по-другому сетить параметры

**Comment by hunterok727** [comment]
возможно все же лучше переписать эту строку в api/index.php
```php
Request::setRawParams([$id, $relation, $relationId]);
//to
$params = [];
foreach ([$id, $relation, $relationId] as $param) {
  if (!is_null($param)) {
     $params[] = $param;
}
}
```

**Comment by hunterok727** [comment]
создал пулл реквест
