### ISSUE TITLE
METHOD_CLI

### ISSUE THREAD

**Issue by ParkFramework** [bluzphp/framework#329]
Если в telnet сделать HTTP запрос, методом cli, в переменой ``$_SERVER['REQUEST_METHOD']``
будет значения - ``cli``.

**Comment by AntonShevchuk** [comment]
Скиньте пример запроса

**Comment by ParkFramework** [comment]
Воспроизводится, если писать CLI в верхнем регистре.
```
telnet localhost 80
CLI /test.php HTTP/1.1
Host: host.dev

HTTP/1.1 200 OK
Server: nginx/1.9.1
Date: Mon, 08 Jun 2015 17:34:19 GMT
Content-Type: text/html; charset=UTF-8
Transfer-Encoding: chunked
Connection: keep-alive
X-Powered-By: PHP/5.6.9

CLI

```

Файл, test.php
```php
<?php

echo $_SERVER['REQUEST_METHOD'];

?>
```

**Comment by AntonShevchuk** [comment]
Метод `\Bluz\Proxy\Request::isCli()` корректно отрабатывает данный запрос и возвращает `false`
