### ISSUE TITLE
Create Helper functions

### ISSUE THREAD

**Issue by Dyachenko** [bluzphp/framework#348]
Create helper functions like http://laravel.com/docs/5.1/helpers or http://kohanaframework.org/3.2/guide/kohana/helpers and use them in code.  It's very cool and useful )

**Comment by AntonShevchuk** [comment]
На данный момент добавлены следующие функции:
- `array_get()`
- `array_has()`
- `array_set()`
- `array_add()`
- `value()`

Остальные по мере надобности, и под них будут созданы отдельные issues
